export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_LOADING_FAILED = "PRODUCTS_LOADING_FAILED";
export const PRODUCTS_LOADING_SUCCESS = "USERS_LOADING_SUCCESS";
export const SET_PRODUCTS = "SET_PRODUCTS";
