export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_LOADING_FAILED = "PRODUCTS_LOADING_FAILED";
export const PRODUCTS_LOADING_SUCCESS = "PRODUCTS_LOADING_SUCCESS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_MISSED_PRODUCTS = "SET_MISSED_PRODUCTS";
export const SET_CATEGORIES = "SET_CATEGORIES";
