export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_LOADING_FAILED = "PRODUCTS_LOADING_FAILED";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
